# themes from https://github.com/alacritty/alacritty-theme

# import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
# import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]


[font]
size = 35

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
