#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
# mkdir -p "$XDG_CONFIG_HOME"/alacritty
# mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
mkdir -p "$XDG_CONFIG_HOME"/k9s
# mkdir -p "$XDG_CONFIG_HOME"/wezterm

# git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes

# set up git prompt
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME"/bash/git-prompt.sh

# Symbolic links

# ln -s ./.amethyst.yml "$HOME"/.amethyst.yml
# ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.zprofile" "$HOME"/.zprofile
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/starship/starship.toml" "$XDG_CONFIG_HOME"/starship.toml
# ln -sf "$PWD/wezterm.lua" /mnt/c/Users/PD2

# Packages

sudo apt-get update
sudo apt install gcc g++ unzip
sudo apt install build-essential
sudo apt install zsh

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# brew install alacritty

# brew packages Mac
# amethyst fzf nvim exa hugo bash-completion@2 newsboat kubectl starship


# GitHub CLI
brew install gh

brew install fd fzf jq yq ripgrep

# kubernetes tools
brew install kubectl kubectx derailed/k9s/k9s

# Install rust. Recommended to use rustup.
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# more langs
brew install go python

# neovim and distro
brew install neovim lazygit

# cross platform shell prompt
brew install starship

# alternative editor to vim & nvim
brew install helix

# Install devbox for emphemeral dev enviroments
# Installs Nix if not already on machine.
curl -fsSL https://get.jetpack.io/devbox | bash

# Install 'uv', Python package & project manager from Astral
curl -LsSf https://astral.sh/uv/install.sh | sh

# Fonts
chmod +x ./scripts/fonts
./scripts/fonts


# Change shell to zsh
# type -a zsh ## find path to zsh ##
chsh -s /bin/zsh ## change bash to zsh ##
