#!/bin/bash

# Declare an array of Nerd Fonts
declare -a fonts=(
    JetBrainsMono Mononoki NerdFontsSymbolsOnly Ubuntu UbuntuMono
)

# Set the Nerd Fonts version
version='3.1.1'

# Specify the directory for installing fonts
fonts_dir="${HOME}/.local/share/fonts"

# Create the fonts directory if it doesn't exist
if [[ ! -d "$fonts_dir" ]]; then
    mkdir -p "$fonts_dir"
fi

# Download and install each Nerd Font
for font in "${fonts[@]}"; do
    zip_file="${font}.zip"
    download_url="https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/${zip_file}"
    echo "Downloading $download_url"
    wget "$download_url"
    unzip "$zip_file" -d "$fonts_dir" -x "*.txt/*" -x "*.md/*"
    rm "$zip_file"
done

# Update the font cache
fc-cache -fv
